name: Learn github actions with R

run-name: Testing R code

on:
    workflow_call:
    push:
        branches-ignore:
            - main
    pull_request:
        branches:
            - main

jobs:
    test-code:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup R
              uses: r-lib/actions/setup-r@v2

            - name: install packages
              run: |
                Rscript -e 'install.packages(c("renv","testthat","lintr"))'
                Rscript -e 'renv::restore()'

            - name: Lint with lintr
              run: Rscript -e 'lintr::lint_dir("R")'

            - name: Test with testthat
              id: run-tests
              run: Rscript -e 'testthat::test_dir("tests/testthat")'

            - name: Upload test report
              run: Rscript -e 'print("Must upload test report here")'
